# Generated by Django 5.2.3 on 2025-07-04 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_product_productimage_productsize_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(help_text='HTML-код кольору, напр. #000000', max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='about',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_guide',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='model_height',
            field=models.PositiveIntegerField(blank=True, help_text='Зріст моделі в см', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_size',
            field=models.CharField(blank=True, help_text='Розмір одягу на моделі (наприклад, S)', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.color'),
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
