# Generated by Django 5.2.3 on 2025-07-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_address_helprequest_order_paymentmethod_return_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='care',
            field=models.TextField(blank=True, help_text='Про догляд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='extra_details',
            field=models.TextField(blank=True, help_text='Про мене'),
        ),
    ]
