# Generated by Django 5.2.3 on 2025-08-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_product_main_image_alter_product_care_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gendr',
            field=models.BooleanField(default=False, help_text='Познач, якщо це чоловічий товар. Якщо ні — буде вважатися жіночим.', verbose_name='Цей товар для чоловіків?'),
        ),
    ]
