# Generated by Django 5.2.3 on 2025-08-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_gendr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='gendr',
            new_name='gender',
        ),
    ]
