# Generated by Django 5.2.3 on 2025-08-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_gendr_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Жіноче'), (1, 'Чоловіче')], default=0),
        ),
    ]
