# Generated by Django 5.2.3 on 2025-08-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='extra_details',
            new_name='about_me',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='care',
            new_name='look_after_me',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='product_details',
            field=models.TextField(blank=True, help_text='Деталі продукту'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1, help_text='Кількість доступних одиниць товару'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(choices=[('M', 'Чоловік'), ('F', 'Жінка')], max_length=1),
        ),
    ]
