# Generated by Django 5.2.3 on 2025-08-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_extra_details_product_about_me_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_size',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Знижка у відсотках'),
        ),
        migrations.AlterField(
            model_name='product',
            name='about_me',
            field=models.TextField(blank=True, default='Машинне прання згідно з інструкціями на етикетках з догляду', help_text='Про мене'),
        ),
    ]
