# Generated by Django 5.0.14 on 2025-09-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_product_model_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lengths',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='about_me',
            field=models.TextField(blank=True, help_text='Про мене'),
        ),
        migrations.AlterField(
            model_name='product',
            name='look_after_me',
            field=models.TextField(blank=True, default='Машинне прання згідно з інструкціями на етикетках з догляду', help_text='Про догляд'),
        ),
    ]
