# Generated by Django 5.2.3 on 2025-09-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_product_lengths_product_sizes_alter_product_about_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
