# Generated by Django 5.2.3 on 2025-09-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_product_discount_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pattern',
            field=models.CharField(choices=[('none', 'Відсутній'), ('striped', 'Смугастий'), ('checked', 'Клітинка'), ('floral', 'Квітковий'), ('other', 'Інший')], default='none', max_length=20, verbose_name='Візерунок'),
        ),
    ]
