# Generated by Django 5.2.3 on 2025-09-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clothing_style',
            field=models.CharField(choices=[('relaxed_straight', 'Розслаблений прямий'), ('loose_straight', 'Вільний прямий'), ('relaxed_arrow', 'Розслаблена стрілка'), ('loose', 'Вільний'), ('baggy', 'Мішковина'), ('straight', 'Прямий'), ('fitted', 'Приталений')], default='loose_straight', max_length=50, verbose_name='Загальний вид одягу'),
        ),
        migrations.AddField(
            model_name='product',
            name='stretchiness',
            field=models.CharField(choices=[('low', 'Низька'), ('medium', 'Середня'), ('high', 'Висока')], default='medium', max_length=20, verbose_name='Розтяжність'),
        ),
    ]
