# Generated by Django 5.2.3 on 2025-09-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shipped', 'В дорозі'), ('cancelled', 'Скасовано')], default='shipped', max_length=10),
        ),
    ]
