# Generated by Django 5.2.3 on 2025-09-30 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_order_status_order_total_price_and_more'),
        ('order', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
