# Generated by Django 5.2.3 on 2025-09-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_order_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
